---
title: "HW8"
output: html_document
date: "2024-02-13"
---

# 1
> If the proportions in the contingency table represented probabilities, would drink preference and sugar preference be independent?

No, the probabilities would not be indepedent because two variables are being considered together. If knowing information about one variable gives us information about another, then they are not independent. 

# 2 
> Is a preference for Cola positively or negatively or not associated with a preference for regular sugar?

There is no association between a preference for cola and regular sugar. This is evident in the fact that the column probability is 50%

# 3
>What can you conclude from this data about the effectiveness of the more toxic treatment?

This is an example of seeing versus doing. Taking the toxic medicine may result in more people experiecning migranes, but it does not mean that not taking toxic treatment will increase  mirganes. Therefore, we cannot conclude anything about more more toxic treatment because we do not have enough information. 




