    source("https://tgstewart.cloud/mystery.R")

    mystery(12)

    ##    location vowel
    ## 1         2     o
    ## 2         2     o
    ## 3         3     a
    ## 4         3     e
    ## 5         2     e
    ## 6         2     i
    ## 7         1     o
    ## 8         2     u
    ## 9         2     i
    ## 10        2     o
    ## 11        2     e
    ## 12        4     o

# Question 1

> We are given that Y will be the vowel, and the want to know the
> probability that the location will be 3. Therefore, we are looking for
> P(3|y).

\#Here is the table we can use to anwser the questions manually.

    require(dplyr)

    ## Loading required package: dplyr

    ## 
    ## Attaching package: 'dplyr'

    ## The following objects are masked from 'package:stats':
    ## 
    ##     filter, lag

    ## The following objects are masked from 'package:base':
    ## 
    ##     intersect, setdiff, setequal, union

    set.seed(223589213)
    d1 <- mystery(10000000) |> mutate(vowel = ifelse(is.na(vowel), "zMissing",vowel))
    descr::CrossTable(
          d1$location
        , d1$vowel
        , prop.chisq = FALSE
    )

    ##    Cell Contents 
    ## |-------------------------|
    ## |                       N | 
    ## |           N / Row Total | 
    ## |           N / Col Total | 
    ## |         N / Table Total | 
    ## |-------------------------|
    ## 
    ## ====================================================================================================
    ##                d1$vowel
    ## d1$location           a          e          i          o          u          y   zMissing      Total
    ## ----------------------------------------------------------------------------------------------------
    ## 1               1044279     288746     603800     574432     159363       4377          0    2674997
    ##                   0.390      0.108      0.226      0.215      0.060      0.002      0.000      0.267
    ##                   0.427      0.124      0.366      0.223      0.256      0.046      0.000           
    ##                   0.104      0.029      0.060      0.057      0.016      0.000      0.000           
    ## ----------------------------------------------------------------------------------------------------
    ## 2               1032774    1315858     758888    1614227     400706      80725          0    5203178
    ##                   0.198      0.253      0.146      0.310      0.077      0.016      0.000      0.520
    ##                   0.422      0.563      0.459      0.626      0.643      0.852      0.000           
    ##                   0.103      0.132      0.076      0.161      0.040      0.008      0.000           
    ## ----------------------------------------------------------------------------------------------------
    ## 3                355094     679234     263030     357058      58043       9451          0    1721910
    ##                   0.206      0.394      0.153      0.207      0.034      0.005      0.000      0.172
    ##                   0.145      0.291      0.159      0.139      0.093      0.100      0.000           
    ##                   0.036      0.068      0.026      0.036      0.006      0.001      0.000           
    ## ----------------------------------------------------------------------------------------------------
    ## 4                 11866      33965      20019      24810       4598        162          0      95420
    ##                   0.124      0.356      0.210      0.260      0.048      0.002      0.000      0.010
    ##                   0.005      0.015      0.012      0.010      0.007      0.002      0.000           
    ##                   0.001      0.003      0.002      0.002      0.000      0.000      0.000           
    ## ----------------------------------------------------------------------------------------------------
    ## 5                  2778      16797       5438       3637        777         32          0      29459
    ##                   0.094      0.570      0.185      0.123      0.026      0.001      0.000      0.003
    ##                   0.001      0.007      0.003      0.001      0.001      0.000      0.000           
    ##                   0.000      0.002      0.001      0.000      0.000      0.000      0.000           
    ## ----------------------------------------------------------------------------------------------------
    ## 6                  1018        783        579       2305         43         39          0       4767
    ##                   0.214      0.164      0.121      0.484      0.009      0.008      0.000      0.000
    ##                   0.000      0.000      0.000      0.001      0.000      0.000      0.000           
    ##                   0.000      0.000      0.000      0.000      0.000      0.000      0.000           
    ## ----------------------------------------------------------------------------------------------------
    ## 7                    49        198         46        229         21          3          0        546
    ##                   0.090      0.363      0.084      0.419      0.038      0.005      0.000      0.000
    ##                   0.000      0.000      0.000      0.000      0.000      0.000      0.000           
    ##                   0.000      0.000      0.000      0.000      0.000      0.000      0.000           
    ## ----------------------------------------------------------------------------------------------------
    ## 8                    10          1         16         40          4          0          0         71
    ##                   0.141      0.014      0.225      0.563      0.056      0.000      0.000      0.000
    ##                   0.000      0.000      0.000      0.000      0.000      0.000      0.000           
    ##                   0.000      0.000      0.000      0.000      0.000      0.000      0.000           
    ## ----------------------------------------------------------------------------------------------------
    ## 9                    89          3          0          1          1          0          0         94
    ##                   0.947      0.032      0.000      0.011      0.011      0.000      0.000      0.000
    ##                   0.000      0.000      0.000      0.000      0.000      0.000      0.000           
    ##                   0.000      0.000      0.000      0.000      0.000      0.000      0.000           
    ## ----------------------------------------------------------------------------------------------------
    ## 10                    0          0          2          1          0          0          0          3
    ##                   0.000      0.000      0.667      0.333      0.000      0.000      0.000      0.000
    ##                   0.000      0.000      0.000      0.000      0.000      0.000      0.000           
    ##                   0.000      0.000      0.000      0.000      0.000      0.000      0.000           
    ## ----------------------------------------------------------------------------------------------------
    ## Inf                   0          0          0          0          0          0     269555     269555
    ##                   0.000      0.000      0.000      0.000      0.000      0.000      1.000      0.027
    ##                   0.000      0.000      0.000      0.000      0.000      0.000      1.000           
    ##                   0.000      0.000      0.000      0.000      0.000      0.000      0.027           
    ## ----------------------------------------------------------------------------------------------------
    ## Total           2447957    2335585    1651818    2576740     623556      94789     269555   10000000
    ##                   0.245      0.234      0.165      0.258      0.062      0.009      0.027           
    ## ====================================================================================================

> We need the conditional column probability from this table, which is
> 0.100.

# Question 2

> We are given that the location is 1 and we want to know what vowel is
> most likely going to be in location 1. If we look in row 1, we see
> that the highest conditional row prabability occurs for a, so P(a|1) =
> 0.39

# Question 3

> We can use the same stratigey as above, but instead of location 1 we
> are looking at location 4. Therefore, we want to know given location 4
> which vowel is most likely to appear in that position. In row 4, we
> see e has the highest conditional row probability, so P(e|4) = 0.356.

# Question 4

> we are looking at the marginal probability for no vowels, which os
> P(Inf) = 0.027

# Question 5

> We will use the margines and look for P(odd), which will equal the sum
> of the odd numbered rows divided by the total. P(odd) = (2674997 +
> 1721910 + 29459 + 546 + 94)/10000000 = 0.4427006. Therefore, It is
> more likley for vowels to be in an even position

> We can also use this code to get an anwser:

    mystery(100000) |> 
      mutate(event = location%%2) |>
      pull(event) |>
      table(useNA = "always") |>
      proportions()

    ## 
    ##       0       1     NaN    <NA> 
    ## 0.53194 0.44181 0.02625 0.00000
